### ISSUE TITLE
WIN 10下获取群成员列表报错

### ISSUE THREAD

**Issue by thesadboy** [stkevintan/node-wcferry#1]
windows 10系统下面调用 getChatRoomMembers 报错，报错信息如下：

Error: Assertion failed
    at jspb.asserts.doAssertFailure (C:\Users\Nick\Desktop\awakening-robot-old\node_modules\google-protobuf\google-protobuf.js:88:597)
    at jspb.asserts.assert (C:\Users\Nick\Desktop\awakening-robot-old\node_modules\google-protobuf\google-protobuf.js:88:729)
    at jspb.BinaryReader.readInt32 (C:\Users\Nick\Desktop\awakening-robot-old\node_modules\google-protobuf\google-protobuf.js:395:371)
    at RoomData.deserialize (C:\Users\Nick\Desktop\awakening-robot-old\node_modules\@wcferry\core\src\lib\proto-generated\roomdata.js:163:58)
    at Wcferry.getChatRoomMembers (C:\Users\Nick\Desktop\awakening-robot-old\node_modules\@wcferry\core\src\lib\client.js:220:54)
    at Module.getRoomMembers (file:///C:/Users/Nick/Desktop/awakening-robot-old/src/wechat.js:54:32)
    at file:///C:/Users/Nick/Desktop/awakening-robot-old/index.js:8:34

Node.js v18.19.0

**Comment by thesadboy** [comment]
```
import protobuf, { Reader } from 'protobufjs'

const RoomData = protobuf.loadSync('./roomdata.proto').lookupType('com.iamteer.wcf.RoomData')
/**
 * 解码
 * @param {Reader | Uint8Array} buf
 */
const decode = (buf: Reader | Uint8Array) => RoomData.decode(buf).toJSON()
export default {
  decode
}
```

目前暂时通过protobufjs库重写来解决了。。。

**Comment by dr-forget** [comment]
问下大佬 加密的xml怎么解密

**Comment by dr-forget** [comment]
> ./roomdata.proto

大佬我已遇到了该问题 请问一下 这个代码要加在什么位置吗

**Comment by dr-forget** [comment]
> RoomData

getMsgTypes Api 也有该问题 同样的错误  麻烦大佬解答一下 详细的解决流程

**Comment by passby6someone** [comment]
> > RoomData
> 
> getMsgTypes Api 也有该问题 同样的错误 麻烦大佬解答一下 详细的解决流程

我不清楚那个大佬怎么修复的 getChatRoomMembers 

但是 ```MsgTypes``` 的 ```proto``` 得改成

```
message MsgType {
    int32   code = 1;
    string  label = 2;
}

message MsgTypes { 
    repeated MsgType types = 1;
}
```

这样才能正常解析，不知道是版本问题还是基础库的```proto```写的有问题
